project_name: go-pcap2socks
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
nfpms:
  - maintainer: Daniil Sokolyuk <danoov@gmail.com>
    description: Sample project.
    homepage: https://github.com/DaniilSokolyuk/go-pcap2socks
    license: GPL-3.0
    formats:
      - deb
      - rpm
      - apk