version: 2

project_name: go-pcap2socks
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - x86
nfpms:
  - maintainer: Daniil Sokolyuk <danoov@gmail.com>
    description: Sample project.
    homepage: https://github.com/DaniilSokolyuk/go-pcap2socks
    license: GPL-3.0