project_name: go-pcap2socks
builds:
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
nfpms:
  - maintainer: Daniil Sokolyuk <danoov@gmail.com>
    description: Sample project.
    homepage: https://github.com/DaniilSokolyuk/go-pcap2socks
    license: GPL-3.0
    formats:
      - deb
      - rpm
      - apk