name: build

on:
  pull_request:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/
          sudo apt-get update --fix-missing
          sudo apt-get install -y libpcap-dev
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install -y libpcap-dev:arm64
      - run: go mod tidy
      - run: go test -v ./...
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: build --id linux --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: brew install libpcap
      - run: go mod tidy
      - run: go test -v ./...
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: build --id darwin --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}