name: build

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: sudo apt-get install -y libpcap-dev
      - run: go mod tidy
      - run: go test -v ./...
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: build --id linux --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: brew install libpcap
      - run: go mod tidy
      - run: go test -v ./...
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: build --id darwin --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}